export const LISTINDEX = "LISTINDEX";
export const TILEINDEX = "TILEINDEX";
export const REDUCE_TILEINDEX = "REDUCE_TILEINDEX";
export const REDUCE_LISTINDEX = "REDUCE_LISTINDEX";
export const RESETINDEX = "RESETINDEX";
export const INCREASE_WORD = "INCREASE_WORD";
export const DECREASE_WORD = "DECREASE_WORD";
export const WORLDE = "WORDLE";
